### ISSUE TITLE
Multi-spec support?

### ISSUE THREAD

**Issue by didibus** [lambdaisland/uniontypes#7]
I admit, I'm confused with the difference between s/or and multi-spec, but it appears that s/or is for closed sum types, and multi-spec is for open sum types. In that regard, would it be possible to have case-of support multi-spec?

**Comment by plexus** [comment]
I'm not sure what would go into making that happen. This library is in passive maintenance mode, meaning I'll review and merge PRs given they are up to standard and fit in with the project, but I'm not actively using or developing this project at the moment.

If someone wants to tackle this then please post a proposal of what the API would look like, and we can take it from there.

**Comment by alysbrooks** [comment]
Closing because this is unlikely to be a priority in the near future. If someone is interested, I recommend submitting a proposal first (rather than a PR), as Arne suggested above.
